from setuptools import setup

setup(
    name='gg',
    version='0.1',
    packages=['venv.lib.python3.6.site-packages.py', 'venv.lib.python3.6.site-packages.py._io',
              'venv.lib.python3.6.site-packages.py._log', 'venv.lib.python3.6.site-packages.py._code',
              'venv.lib.python3.6.site-packages.py._path', 'venv.lib.python3.6.site-packages.py._process',
              'venv.lib.python3.6.site-packages.py._vendored_packages', 'venv.lib.python3.6.site-packages.bs4',
              'venv.lib.python3.6.site-packages.bs4.tests', 'venv.lib.python3.6.site-packages.bs4.builder',
              'venv.lib.python3.6.site-packages.rsa', 'venv.lib.python3.6.site-packages.attr',
              'venv.lib.python3.6.site-packages.idna', 'venv.lib.python3.6.site-packages.yaml',
              'venv.lib.python3.6.site-packages.build', 'venv.lib.python3.6.site-packages.Naked',
              'venv.lib.python3.6.site-packages.Naked.commands', 'venv.lib.python3.6.site-packages.Naked.toolshed',
              'venv.lib.python3.6.site-packages.Naked.toolshed.c', 'venv.lib.python3.6.site-packages.Naked.templates',
              'venv.lib.python3.6.site-packages.crypto', 'venv.lib.python3.6.site-packages.crypto.tools',
              'venv.lib.python3.6.site-packages.crypto.library', 'venv.lib.python3.6.site-packages.crypto.symmetric',
              'venv.lib.python3.6.site-packages.crypto.asymmetric', 'venv.lib.python3.6.site-packages.pluggy',
              'venv.lib.python3.6.site-packages.pyasn1', 'venv.lib.python3.6.site-packages.pyasn1.type',
              'venv.lib.python3.6.site-packages.pyasn1.codec', 'venv.lib.python3.6.site-packages.pyasn1.codec.ber',
              'venv.lib.python3.6.site-packages.pyasn1.codec.cer', 'venv.lib.python3.6.site-packages.pyasn1.codec.der',
              'venv.lib.python3.6.site-packages.pyasn1.codec.native', 'venv.lib.python3.6.site-packages.pyasn1.compat',
              'venv.lib.python3.6.site-packages._pytest', 'venv.lib.python3.6.site-packages._pytest.mark',
              'venv.lib.python3.6.site-packages._pytest._code', 'venv.lib.python3.6.site-packages._pytest.assertion',
              'venv.lib.python3.6.site-packages.certifi', 'venv.lib.python3.6.site-packages.chardet',
              'venv.lib.python3.6.site-packages.chardet.cli', 'venv.lib.python3.6.site-packages.urllib3',
              'venv.lib.python3.6.site-packages.urllib3.util', 'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.dateutil', 'venv.lib.python3.6.site-packages.dateutil.tz',
              'venv.lib.python3.6.site-packages.dateutil.parser', 'venv.lib.python3.6.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.6.site-packages.httplib2', 'venv.lib.python3.6.site-packages.requests',
              'venv.lib.python3.6.site-packages.selenium', 'venv.lib.python3.6.site-packages.selenium.common',
              'venv.lib.python3.6.site-packages.selenium.webdriver',
              'venv.lib.python3.6.site-packages.selenium.webdriver.ie',
              'venv.lib.python3.6.site-packages.selenium.webdriver.edge',
              'venv.lib.python3.6.site-packages.selenium.webdriver.opera',
              'venv.lib.python3.6.site-packages.selenium.webdriver.chrome',
              'venv.lib.python3.6.site-packages.selenium.webdriver.common',
              'venv.lib.python3.6.site-packages.selenium.webdriver.common.html5',
              'venv.lib.python3.6.site-packages.selenium.webdriver.common.actions',
              'venv.lib.python3.6.site-packages.selenium.webdriver.remote',
              'venv.lib.python3.6.site-packages.selenium.webdriver.safari',
              'venv.lib.python3.6.site-packages.selenium.webdriver.android',
              'venv.lib.python3.6.site-packages.selenium.webdriver.firefox',
              'venv.lib.python3.6.site-packages.selenium.webdriver.support',
              'venv.lib.python3.6.site-packages.selenium.webdriver.phantomjs',
              'venv.lib.python3.6.site-packages.selenium.webdriver.webkitgtk',
              'venv.lib.python3.6.site-packages.selenium.webdriver.blackberry',
              'venv.lib.python3.6.site-packages.apiclient', 'venv.lib.python3.6.site-packages.autoclass',
              'venv.lib.python3.6.site-packages.autoclass.tests', 'venv.lib.python3.6.site-packages.shellescape',
              'venv.lib.python3.6.site-packages.uritemplate', 'venv.lib.python3.6.site-packages.oauth2client',
              'venv.lib.python3.6.site-packages.oauth2client.contrib',
              'venv.lib.python3.6.site-packages.oauth2client.contrib.django_util',
              'venv.lib.python3.6.site-packages.more_itertools',
              'venv.lib.python3.6.site-packages.more_itertools.tests',
              'venv.lib.python3.6.site-packages.pyasn1_modules', 'venv.lib.python3.6.site-packages.googleapiclient',
              'venv.lib.python3.6.site-packages.googleapiclient.discovery_cache'],
    url='v4online.ru',
    license='MT',
    author='mikhail.shchegolev',
    author_email='mshegolev@gmail.com',
    description='tests example'
)
